name: myapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:

    sdk: flutter
  http: ^0.13.3
  flutter_secure_storage: ^4.1.0
  any_widget_marquee: ^1.0.2
  bottom_navy_bar: ^6.0.0
  geocoding: ^2.0.0
  geolocator: ^7.6.0
  shared_preferences: ^2.0.5
  encrypt: ^5.0.0
  uuid: ^3.0.4
  device_info: ^2.0.0
  intro_slider: ^2.3.4
  geocoder: ^0.2.1
  carousel_pro: ^1.0.0
  flutter_svg: ^0.22.0
  connectivity: ^3.0.6
  sms_autofill: ^2.0.0
  image_gallery_saver: '^1.6.9'
  path_provider: ^2.0.2
  intl: ^0.17.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  carousel_slider: ^0.0.7
  sticky_headers: ^0.2.0
  progress_indicators: ^1.0.0
  fluttercontactpicker: ^4.5.1
  search_choices: ^2.0.3
  permission_handler: ^8.0.1
  flutter_chat_bubble: ^1.0.2
  flutter_advanced_switch: ^2.1.0
  dependencies:

  image_downloader: ^0.30.0
  image_picker: ^0.8.0+3
  video_player: ^0.11.1+2
  url_launcher: ^6.0.6
  video_compress: ^3.0.0
  share: ^2.0.4
  safexpay: ^0.0.9
  usb_serial: ^0.3.0
  marquee_widget: ^1.2.0
  upi_pay: ^1.0.1
  firebase_messaging: ^10.0.5
  firebase_core: ^1.5.0
  flutter_local_notifications: ^8.1.1+1
  local_auth: ^1.1.7
  google_maps_flutter: ^0.5.21
  upi_india: ^3.0.1
  flutter_localizations:
    sdk: flutter
  printing: ^5.6.5
  cool_alert: ^1.1.0
  simple_wave: ^0.0.3
  custom_switch: ^0.0.1
  animated_text_kit: ^4.2.1
  firebase_messaging_platform_interface: 3.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/pngImages/
    - assets/
    - assets/images/
    - assets/SL02.png
    - assets/Sl4.png
    - assets/aashalogo.png
    - assets/icons/news.png
    - assets/pngImages/warningg.png
    - assets/aashalogo.png
    - assets/language/en.json
    - assets/language/es.json
    - assets/language/fr.json
    - assets/language/hi.json
    - assets/language/mr.json
    - assets/language/gu.json
    - assets/language/ta.json

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
